### ISSUE TITLE
Basic Menus

### ISSUE THREAD

**Issue by AtoraSuunva** [InfinityDeer/Unity-Project#3]
- [x] Main menu,
- [x] Pause menu,
- [ ] Settings menu...

**Comment by InfinityDeer** [comment]
-Basic Main Menu Completed

**Comment by InfinityDeer** [comment]
-Started working settings menu

**Comment by InfinityDeer** [comment]
-Settings menu delayed, needs more work first.

**Comment by InfinityDeer** [comment]
-Pause Menu Completed
