### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by AtoraSuunva** [InfinityDeer/Unity-Project#4]
Change game settings.

Things like camera, volume, controls (?)

**Comment by InfinityDeer** [comment]
-Basic Graphics Settings Added 

[Highest]
![graphics_fantastic_1](https://cloud.githubusercontent.com/assets/19762143/16032569/b4b58a86-31d4-11e6-9da7-fa412c0b0b04.png)

[Lowest]
![graphics_fastest_1](https://cloud.githubusercontent.com/assets/19762143/16032566/abc350d4-31d4-11e6-877c-cf3170127015.png)
